<?php

namespace Informat\Object;

use Informat\Interface\CustomObject;

class StudentExtra extends CustomObject
{
	protected $objectAttributes = [
		"pointer",
		"naam",
		"voornaam",
		"Tweedevoornaam",
		"Sorteernaam",
		"geboortedatum",
		"geboorteplaats",
		"geboorteland",
		"geslacht",
		"initialen",
		"nationaliteit",
		"aanspreektitel",
		"aanspreeknaam",
		"straat",
		"nr",
		"bus",
		"hfdpostnr",
		"hfdgem",
		"land",
		"domicilietelefoon",
		"GSMeigen",
		"GSMvader",
		"GSMmoeder",
		"Noodtelefoon",
		"telefoonVader",
		"telefoonMoeder",
		"telefoonWerkVader",
		"telefoonWerkMoeder",
		"Rijksregisternummer",
		"BISnummer",
		"VoornaamVader",
		"NaamVader",
		"BeroepVader",
		"DiplomaVader",
		"OpmerkingVader",
		"BurgerlijkeStaatVader",
		"NationaliteitVader",
		"VaderOverleden",
		"GeboortedatumVader",
		"VoornaamMoeder",
		"NaamMoeder",
		"BeroepMoeder",
		"DiplomaMoeder",
		"OpmerkingMoeder",
		"BurgerlijkeStaatMoeder",
		"NationaliteitMoeder",
		"MoederOverleden",
		"GeboortedatumMoeder",
		"EmailSchool",
		"EmailEigen",
		"EmailOuders",
		"EmailMoeder",
		"EmailVader",
		"EmailPrive",
		"Stamnummer",
		"Levensbeschouwing",
		"Huisdokter",
		"TelefoonHuisdokter",
		"Verblijfstype",
		"Internaat",
		"Llnkaartnr",
		"Fietsnummer",
		"TelefoonInstelling",
		"PSchoolVest"
	];
}
